import PIL.Image as Image
import numpy as np
import cv2 as cv2
from matplotlib import pyplot as plt

fileList = [
   'clipSampleDone/aaa/A/cell01-gray_0x3.png',
   'clipSampleDone/aaa/A/cell01-gray_3x9 copy 2.png',
   'clipSampleDone/aaa/A/cell01-gray_3x9 copy.png',
   'clipSampleDone/aaa/A/cell01-gray_9x0 copy 2.png',
   'clipSampleDone/aaa/A/cell01-gray_9x0 copy.png',
   'clipSampleDone/aaa/A/cell01-gray_9x3 copy 2.png',
   'clipSampleDone/aaa/A/cell01-gray_9x3 copy.png',
   'clipSampleDone/aaa/A/cell02-gray_5x6.png',
   'clipSampleDone/aaa/A/cell02-gray_6x3 copy.png',
   'clipSampleDone/aaa/A/cell02-gray_6x3.png',
   'clipSampleDone/aaa/A/cell02-gray_9x5 copy.png',
   'clipSampleDone/aaa/A/cell03-gray_10x8.png',
   'clipSampleDone/aaa/A/cell03-gray_2x6 copy.png',
   'clipSampleDone/aaa/A/cell03-gray_5x5 copy.png',
   'clipSampleDone/aaa/A/cell04-gray_0x7.png',
   'clipSampleDone/aaa/A/cell04-gray_8x5.png',
   'clipSampleDone/aaa/A/cell04-gray_9x9.png',
   'clipSampleDone/aaa/A/cell05-gray_10x8.png',
   'clipSampleDone/aaa/A/cell05-gray_6x10.png',
   'clipSampleDone/aaa/A/cell05-gray_7x9 copy.png',
   'clipSampleDone/aaa/A/cell05-gray_7x9.png',
   'clipSampleDone/aaa/A/cell06-gray_10x8 copy.png',
   'clipSampleDone/aaa/A/cell06-gray_1x6 copy.png',
   'clipSampleDone/aaa/A/cell06-gray_4x6 copy.png',
   'clipSampleDone/aaa/A/cell06-gray_5x1 copy.png',
   'clipSampleDone/aaa/A/cell07-gray_2x9.png',
   'clipSampleDone/aaa/A/cell07-gray_6x10.png',
   'clipSampleDone/aaa/A/cell07-gray_6x8.png',
   'clipSampleDone/aaa/A/cell07-gray_9x1.png',
   'clipSampleDone/aaa/A/cell08-gray_0x8.png',
   'clipSampleDone/aaa/A/cell08-gray_1x10.png',
   'clipSampleDone/aaa/A/cell08-gray_1x4.png',
   'clipSampleDone/aaa/A/cell08-gray_2x1 copy.png',
   'clipSampleDone/aaa/A/cell08-gray_2x1.png',
   'clipSampleDone/aaa/A/cell08-gray_5x2.png',
   'clipSampleDone/aaa/A/cell08-gray_5x5.png',
   'clipSampleDone/aaa/A/cell08-gray_8x2.png',
   'clipSampleDone/aaa/A/cell08-gray_8x5.png',
   'clipSampleDone/aaa/A/cell08-gray_9x9.png',
   'clipSampleDone/aaa/B/cell01-gray_0x7 copy.png',
   'clipSampleDone/aaa/B/cell01-gray_0x7.png',
   'clipSampleDone/aaa/B/cell03-gray_2x0 copy.png',
   'clipSampleDone/aaa/B/cell03-gray_2x0.png',
   'clipSampleDone/aaa/B/cell03-gray_7x5 copy.png',
   'clipSampleDone/aaa/B/cell03-gray_8x4.png',
   'clipSampleDone/aaa/B/cell04-gray_3x4 copy.png',
   'clipSampleDone/aaa/B/cell05-gray_0x7 copy.png',
   'clipSampleDone/aaa/B/cell05-gray_0x7.png',
   'clipSampleDone/aaa/B/cell05-gray_3x8 copy.png',
   'clipSampleDone/aaa/B/cell05-gray_3x8.png',
   'clipSampleDone/aaa/B/cell06-gray_0x0 copy.png',
   'clipSampleDone/aaa/B/cell06-gray_0x0.png',
   'clipSampleDone/aaa/B/cell08-gray_5x8.png',
   'clipSampleDone/aaa/C/cell01-gray_0x2 copy.png',
   'clipSampleDone/aaa/C/cell01-gray_9x5 copy.png',
   'clipSampleDone/aaa/C/cell02-gray_6x6.png',
   'clipSampleDone/aaa/C/cell03-gray_5x3.png',
   'clipSampleDone/aaa/C/cell04-gray_10x0.png',
   'clipSampleDone/aaa/C/cell04-gray_2x6.png',
   'clipSampleDone/aaa/C/cell04-gray_5x4 copy.png',
   'clipSampleDone/aaa/C/cell05-gray_2x0 copy.png',
   'clipSampleDone/aaa/C/cell05-gray_5x0 copy.png',
   'clipSampleDone/aaa/C/cell05-gray_7x7 copy.png',
   'clipSampleDone/aaa/C/cell06-gray_2x10 copy.png',
   'clipSampleDone/aaa/C/cell06-gray_2x10.png',
   'clipSampleDone/aaa/C/cell06-gray_2x4 copy.png',
   'clipSampleDone/aaa/C/cell07-gray_1x2.png',
   'clipSampleDone/aaa/C/cell07-gray_3x7 copy.png',
   'clipSampleDone/aaa/C/cell08-gray_1x5.png',
   'clipSampleDone/aaa/C/cell08-gray_4x6 copy.png',
   'clipSampleDone/aaa/C/cell08-gray_4x6.png',
   'clipSampleDone/aaa/D/cell01-gray_5x0 copy.png',
   'clipSampleDone/aaa/D/cell01-gray_5x0.png',
   'clipSampleDone/aaa/D/cell01-gray_7x3 copy.png',
   'clipSampleDone/aaa/D/cell02-gray_8x8 copy.png',
   'clipSampleDone/aaa/D/cell02-gray_8x8.png',
   'clipSampleDone/aaa/D/cell03-gray_10x3.png',
   'clipSampleDone/aaa/D/cell04-gray_1x4.png',
   'clipSampleDone/aaa/D/cell06-gray_3x2.png',
   'clipSampleDone/aaa/D/cell07-gray_0x0.png',
   'clipSampleDone/aaa/D/cell08-gray_10x0.png',
   'clipSampleDone/aaa/E/cell02-gray_9x10.png',
   'clipSampleDone/aaa/E/cell03-gray_10x4.png',
   'clipSampleDone/aaa/E/cell04-gray_0x7.png',
   'clipSampleDone/aaa/E/cell04-gray_8x1.png',
   'clipSampleDone/aaa/E/cell05-gray_10x6.png',
   'clipSampleDone/aaa/E/cell08-gray_6x4.png',
   'clipSampleDone/aaa/E/cell08-gray_7x2.png',
   'clipSampleDone/aaa/F/cell01-gray_2x6 copy.png',
   'clipSampleDone/aaa/F/cell02-gray_4x6 copy.png',
   'clipSampleDone/aaa/F/cell04-gray_6x2 copy.png',
   'clipSampleDone/aaa/F/cell08-gray_2x6 copy.png',
   'clipSampleDone/aaa/G/cell01-gray_8x6 copy.png',
   'clipSampleDone/aaa/G/cell02-gray_2x5 copy.png',
   'clipSampleDone/aaa/G/cell02-gray_7x3 copy.png',
   'clipSampleDone/aaa/G/cell04-gray_2x0 copy.png',
   'clipSampleDone/aaa/G/cell05-gray_5x8 copy.png',
   'clipSampleDone/aaa/G/cell05-gray_8x3 copy.png',
   'clipSampleDone/aaa/G/cell06-gray_3x6 copy.png',
   'clipSampleDone/aaa/G/cell06-gray_8x0 copy.png',
   'clipSampleDone/aaa/G/cell08-gray_10x7.png',
   'clipSampleDone/aaa/G/cell08-gray_2x0 copy.png',
   'clipSampleDone/aaa/G/cell08-gray_9x7.png',
   'clipSampleDone/aaa/H/cell01-gray_9x6 copy.png',
   'clipSampleDone/aaa/H/cell02-gray_1x4 copy.png',
   'clipSampleDone/aaa/H/cell02-gray_5x5 copy.png',
   'clipSampleDone/aaa/H/cell03-gray_0x7 copy.png',
   'clipSampleDone/aaa/H/cell04-gray_0x10 copy.png',
   'clipSampleDone/aaa/H/cell05-gray_5x5 copy.png',
   'clipSampleDone/aaa/H/cell05-gray_5x9 copy.png',
   'clipSampleDone/aaa/H/cell06-gray_0x6 copy.png',
   'clipSampleDone/aaa/H/cell06-gray_3x10 copy.png',
   'clipSampleDone/aaa/H/cell06-gray_5x0 copy.png',
   'clipSampleDone/aaa/H/cell06-gray_8x8 copy.png',
   'clipSampleDone/aaa/H/cell06-gray_9x0 copy.png',
   'clipSampleDone/aaa/H/cell08-gray_4x3 copy.png',
   'clipSampleDone/aaa/I/cell01-gray_4x8.png',
   'clipSampleDone/aaa/I/cell02-gray_0x0 copy.png',
   'clipSampleDone/aaa/I/cell02-gray_8x2 copy.png',
   'clipSampleDone/aaa/I/cell03-gray_7x9 copy.png',
   'clipSampleDone/aaa/I/cell04-gray_1x0 copy.png',
   'clipSampleDone/aaa/I/cell04-gray_9x0 copy.png',
   'clipSampleDone/aaa/I/cell05-gray_0x1 copy.png',
   'clipSampleDone/aaa/I/cell05-gray_7x6 copy.png',
   'clipSampleDone/aaa/I/cell06-gray_4x10 copy.png',
   'clipSampleDone/aaa/I/cell06-gray_4x2 copy.png',
   'clipSampleDone/aaa/I/cell06-gray_9x5 copy.png',
   'clipSampleDone/aaa/I/cell08-gray_1x0 copy.png',
   'clipSampleDone/aaa/I/cell08-gray_3x4 copy.png',
   'clipSampleDone/aaa/I/cell08-gray_3x6 copy.png',
   'clipSampleDone/aaa/I/cell08-gray_5x6 copy 3.png',
   'clipSampleDone/aaa/I/cell08-gray_5x6 copy.png',
   'clipSampleDone/aaa/I/cell08-gray_5x6.png',
   'clipSampleDone/aaa/J/cell07-gray_2x8 copy.png',
   'clipSampleDone/aaa/J/cell08-gray_5x6.png',
   'clipSampleDone/aaa/K/cell02-gray_4x4 copy.png',
   'clipSampleDone/aaa/K/cell05-gray_10x2 copy.png',
   'clipSampleDone/aaa/K/cell06-gray_3x0 copy.png',
   'clipSampleDone/aaa/K/cell07-gray_0x7 copy.png',
   'clipSampleDone/aaa/K/cell07-gray_4x7 copy.png',
   'clipSampleDone/aaa/L/cell01-gray_0x4 copy.png',
   'clipSampleDone/aaa/L/cell01-gray_10x2 copy.png',
   'clipSampleDone/aaa/L/cell01-gray_10x3 copy.png',
   'clipSampleDone/aaa/L/cell01-gray_4x4 copy.png',
   'clipSampleDone/aaa/L/cell01-gray_5x5 copy.png',
   'clipSampleDone/aaa/L/cell01-gray_9x8 copy.png',
   'clipSampleDone/aaa/L/cell02-gray_3x6 copy.png',
   'clipSampleDone/aaa/L/cell02-gray_5x2 copy.png',
   'clipSampleDone/aaa/L/cell03-gray_5x6 copy 2.png',
   'clipSampleDone/aaa/L/cell03-gray_6x4 copy.png',
   'clipSampleDone/aaa/L/cell03-gray_7x6 copy.png',
   'clipSampleDone/aaa/L/cell03-gray_8x9 copy.png',
   'clipSampleDone/aaa/L/cell04-gray_3x7 copy.png',
   'clipSampleDone/aaa/L/cell04-gray_6x4 copy.png',
   'clipSampleDone/aaa/L/cell05-gray_7x10 copy.png',
   'clipSampleDone/aaa/L/cell05-gray_8x1 copy.png',
   'clipSampleDone/aaa/L/cell05-gray_9x8 copy.png',
   'clipSampleDone/aaa/L/cell06-gray_0x8 copy.png',
   'clipSampleDone/aaa/L/cell06-gray_0x9 copy.png',
   'clipSampleDone/aaa/L/cell07-gray_4x4 copy.png',
   'clipSampleDone/aaa/M/cell01-gray_10x9 copy.png',
   'clipSampleDone/aaa/M/cell01-gray_5x7 copy.png',
   'clipSampleDone/aaa/M/cell02-gray_1x0 copy.png',
   'clipSampleDone/aaa/M/cell02-gray_5x7 copy.png',
   'clipSampleDone/aaa/M/cell03-gray_0x3 copy.png',
   'clipSampleDone/aaa/M/cell04-gray_0x3 copy.png',
   'clipSampleDone/aaa/M/cell04-gray_4x6 copy.png',
   'clipSampleDone/aaa/M/cell06-gray_10x4 copy.png',
   'clipSampleDone/aaa/M/cell06-gray_10x9 copy.png',
   'clipSampleDone/aaa/M/cell06-gray_5x2 copy.png',
   'clipSampleDone/aaa/M/cell07-gray_0x4 copy.png',
   'clipSampleDone/aaa/M/cell07-gray_3x5 copy.png',
   'clipSampleDone/aaa/M/cell07-gray_4x9 copy.png',
   'clipSampleDone/aaa/M/cell07-gray_5x10 copy.png',
   'clipSampleDone/aaa/N/cell01-gray_1x10 copy.png',
   'clipSampleDone/aaa/N/cell01-gray_2x3 copy.png',
   'clipSampleDone/aaa/N/cell01-gray_5x9 copy.png',
   'clipSampleDone/aaa/N/cell01-gray_7x10 copy.png',
   'clipSampleDone/aaa/N/cell01-gray_8x0 copy.png',
   'clipSampleDone/aaa/N/cell01-gray_8x2 copy.png',
   'clipSampleDone/aaa/N/cell02-gray_0x1 copy.png',
   'clipSampleDone/aaa/N/cell02-gray_10x10 copy.png',
   'clipSampleDone/aaa/N/cell02-gray_1x8 copy.png',
   'clipSampleDone/aaa/N/cell02-gray_2x2 copy.png',
   'clipSampleDone/aaa/N/cell02-gray_2x7 copy.png',
   'clipSampleDone/aaa/N/cell02-gray_3x4 copy.png',
   'clipSampleDone/aaa/N/cell02-gray_9x3 copy.png',
   'clipSampleDone/aaa/N/cell03-gray_1x10 copy.png',
   'clipSampleDone/aaa/N/cell03-gray_5x6.png',
   'clipSampleDone/aaa/N/cell03-gray_7x1 copy.png',
   'clipSampleDone/aaa/N/cell04-gray_10x2 copy.png',
   'clipSampleDone/aaa/N/cell04-gray_3x1 copy.png',
   'clipSampleDone/aaa/N/cell04-gray_4x3 copy.png',
   'clipSampleDone/aaa/N/cell04-gray_5x9 copy.png',
   'clipSampleDone/aaa/N/cell04-gray_7x6.png',
   'clipSampleDone/aaa/N/cell05-gray_0x3 copy.png',
   'clipSampleDone/aaa/N/cell05-gray_10x9 copy.png',
   'clipSampleDone/aaa/N/cell05-gray_1x10 copy.png',
   'clipSampleDone/aaa/N/cell05-gray_2x2 copy.png',
   'clipSampleDone/aaa/N/cell05-gray_2x6 copy.png',
   'clipSampleDone/aaa/N/cell05-gray_3x0 copy.png',
   'clipSampleDone/aaa/N/cell05-gray_5x2 copy.png',
   'clipSampleDone/aaa/N/cell05-gray_9x10 copy.png',
   'clipSampleDone/aaa/N/cell05-gray_9x4 copy.png',
   'clipSampleDone/aaa/N/cell06-gray_1x2.png',
   'clipSampleDone/aaa/N/cell06-gray_2x6 copy.png',
   'clipSampleDone/aaa/N/cell06-gray_4x8 copy.png',
   'clipSampleDone/aaa/N/cell06-gray_7x6 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_0x8 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_10x6 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_1x7 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_2x4 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_3x3 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_4x0 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_5x6 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_7x10 copy.png',
   'clipSampleDone/aaa/N/cell07-gray_8x10 copy.png',
   'clipSampleDone/aaa/N/cell08-gray_2x8 copy.png',
   'clipSampleDone/aaa/N/cell08-gray_3x5 copy.png',
   'clipSampleDone/aaa/N/cell08-gray_9x0 copy.png',
   'clipSampleDone/aaa/O/cell01-gray_1x7 copy.png',
   'clipSampleDone/aaa/O/cell02-gray_1x10 copy.png',
   'clipSampleDone/aaa/O/cell02-gray_3x0 copy.png',
   'clipSampleDone/aaa/O/cell03-gray_1x3 copy.png',
   'clipSampleDone/aaa/O/cell03-gray_8x2 copy.png',
   'clipSampleDone/aaa/O/cell04-gray_10x1 copy.png',
   'clipSampleDone/aaa/O/cell04-gray_1x10 copy.png',
   'clipSampleDone/aaa/O/cell05-gray_1x9.png',
   'clipSampleDone/aaa/O/cell05-gray_3x9 copy.png',
   'clipSampleDone/aaa/O/cell06-gray_10x1 copy.png',
   'clipSampleDone/aaa/O/cell06-gray_2x7 copy.png',
   'clipSampleDone/aaa/O/cell06-gray_7x3 copy.png',
   'clipSampleDone/aaa/O/cell07-gray_0x9 copy.png',
   'clipSampleDone/aaa/O/cell07-gray_1x4 copy.png',
   'clipSampleDone/aaa/O/cell07-gray_3x2 copy.png',
   'clipSampleDone/aaa/O/cell07-gray_3x4 copy.png',
   'clipSampleDone/aaa/O/cell07-gray_5x4 copy.png',
   'clipSampleDone/aaa/O/cell07-gray_5x5 copy.png',
   'clipSampleDone/aaa/O/cell07-gray_6x6.png',
   'clipSampleDone/aaa/O/cell07-gray_7x1 copy.png',
   'clipSampleDone/aaa/O/cell08-gray_4x10 copy.png',
   'clipSampleDone/aaa/O/cell08-gray_5x9 copy.png',
   'clipSampleDone/aaa/O/cell08-gray_7x9 copy.png',
   'clipSampleDone/aaa/P/cell01-gray_3x10 copy.png',
   'clipSampleDone/aaa/P/cell02-gray_0x2 copy.png',
   'clipSampleDone/aaa/P/cell02-gray_2x0 copy.png',
   'clipSampleDone/aaa/P/cell02-gray_5x8 copy.png',
   'clipSampleDone/aaa/P/cell02-gray_6x1 copy.png',
   'clipSampleDone/aaa/P/cell03-gray_2x3 copy.png',
   'clipSampleDone/aaa/P/cell03-gray_5x1 copy.png',
   'clipSampleDone/aaa/P/cell03-gray_8x7 copy.png',
   'clipSampleDone/aaa/P/cell04-gray_8x0 copy.png',
   'clipSampleDone/aaa/P/cell05-gray_0x0 c.png',
   'clipSampleDone/aaa/P/cell05-gray_0x0 copy 2.png',
   'clipSampleDone/aaa/P/cell05-gray_3x4 copy.png',
   'clipSampleDone/aaa/P/cell05-gray_8x0 copy.png',
   'clipSampleDone/aaa/Q/cell01-gray_2x0 copy.png',
   'clipSampleDone/aaa/Q/cell03-gray_6x0 copy.png',
   'clipSampleDone/aaa/R/cell04-gray_7x8 copy 2.png',
   'clipSampleDone/aaa/R/cell07-gray_3x9 copy.png',
   'clipSampleDone/aaa/R/cell07-gray_9x0 copy.png',
   'clipSampleDone/aaa/R/cell08-gray_0x7 copy.png',
   'clipSampleDone/aaa/R/cell08-gray_1x3 copy.png',
   'clipSampleDone/aaa/R/cell08-gray_2x10 copy.png',
   'clipSampleDone/aaa/R/cell08-gray_3x10 copy.png',
   'clipSampleDone/aaa/S/cell01-gray_0x10 copy.png',
   'clipSampleDone/aaa/S/cell01-gray_6x6 copy.png',
   'clipSampleDone/aaa/S/cell01-gray_7x7 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_0x7 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_10x1 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_10x9 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_3x8 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_4x0 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_5x4 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_7x4 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_8x1 copy.png',
   'clipSampleDone/aaa/S/cell02-gray_9x6 copy.png',
   'clipSampleDone/aaa/S/cell03-gray_10x9 copy.png',
   'clipSampleDone/aaa/S/cell03-gray_2x5 copy.png',
   'clipSampleDone/aaa/S/cell03-gray_3x6 copy.png',
   'clipSampleDone/aaa/S/cell03-gray_4x2 copy.png',
   'clipSampleDone/aaa/S/cell03-gray_5x0 copy.png',
   'clipSampleDone/aaa/S/cell03-gray_7x2 copy.png',
   'clipSampleDone/aaa/S/cell03-gray_9x0 copy.png',
   'clipSampleDone/aaa/S/cell03-gray_9x6 copy.png',
   'clipSampleDone/aaa/S/cell04-gray_0x2 copy.png',
   'clipSampleDone/aaa/S/cell04-gray_0x6 copy.png',
   'clipSampleDone/aaa/S/cell04-gray_2x2 copy.png',
   'clipSampleDone/aaa/S/cell04-gray_2x8 copy.png',
   'clipSampleDone/aaa/S/cell04-gray_3x5 copy.png',
   'clipSampleDone/aaa/S/cell04-gray_8x2 copy.png',
   'clipSampleDone/aaa/S/cell04-gray_9x4 copy.png',
   'clipSampleDone/aaa/S/cell05-gray_0x10 copy.png',
   'clipSampleDone/aaa/S/cell05-gray_1x8 copy.png',
   'clipSampleDone/aaa/S/cell05-gray_2x3 copy.png',
   'clipSampleDone/aaa/S/cell06-gray_1x10 copy.png',
   'clipSampleDone/aaa/S/cell06-gray_3x4 copy.png',
   'clipSampleDone/aaa/S/cell06-gray_5x6 copy.png',
   'clipSampleDone/aaa/S/cell06-gray_9x4 copy.png',
   'clipSampleDone/aaa/S/cell07-gray_10x10 copy.png',
   'clipSampleDone/aaa/S/cell07-gray_2x10 copy.png',
   'clipSampleDone/aaa/S/cell08-gray_3x3.png',
   'clipSampleDone/aaa/S/cell08-gray_3x7 copy.png',
   'clipSampleDone/aaa/S/cell08-gray_6x0 copy.png',
   'clipSampleDone/aaa/T/cell01-gray_10x6 copy.png',
   'clipSampleDone/aaa/T/cell01-gray_2x4 copy.png',
   'clipSampleDone/aaa/T/cell01-gray_3x4 copy.png',
   'clipSampleDone/aaa/T/cell01-gray_3x8 copy.png',
   'clipSampleDone/aaa/T/cell01-gray_6x1 copy.png',
   'clipSampleDone/aaa/T/cell02-gray_0x4 copy.png',
   'clipSampleDone/aaa/T/cell02-gray_10x0 copy.png',
   'clipSampleDone/aaa/T/cell02-gray_2x3 copy.png',
   'clipSampleDone/aaa/T/cell02-gray_3x10 copy.png',
   'clipSampleDone/aaa/T/cell02-gray_7x6 copy.png',
   'clipSampleDone/aaa/T/cell02-gray_7x9 copy.png',
   'clipSampleDone/aaa/T/cell02-gray_8x0 copy.png',
   'clipSampleDone/aaa/T/cell03-gray_7x3 copy.png',
   'clipSampleDone/aaa/T/cell03-gray_9x7 copy.png',
   'clipSampleDone/aaa/T/cell04-gray_10x10 copy.png',
   'clipSampleDone/aaa/T/cell04-gray_3x9 copy.png',
   'clipSampleDone/aaa/T/cell04-gray_5x10 copy.png',
   'clipSampleDone/aaa/T/cell05-gray_10x10 copy.png',
   'clipSampleDone/aaa/T/cell05-gray_2x7 copy.png',
   'clipSampleDone/aaa/T/cell05-gray_5x10 copy.png',
   'clipSampleDone/aaa/T/cell05-gray_6x6 copy.png',
   'clipSampleDone/aaa/T/cell05-gray_9x6 copy.png',
   'clipSampleDone/aaa/T/cell06-gray_10x2 copy.png',
   'clipSampleDone/aaa/T/cell06-gray_6x9 copy.png',
   'clipSampleDone/aaa/T/cell06-gray_7x7 copy.png',
   'clipSampleDone/aaa/T/cell06-gray_8x7 copy.png',
   'clipSampleDone/aaa/T/cell07-gray_0x10 copy.png',
   'clipSampleDone/aaa/T/cell07-gray_5x8 copy.png',
   'clipSampleDone/aaa/T/cell07-gray_7x2 copy.png',
   'clipSampleDone/aaa/T/cell07-gray_7x6 copy.png',
   'clipSampleDone/aaa/T/cell08-gray_0x3 copy 2.png',
   'clipSampleDone/aaa/T/cell08-gray_7x10 copy.png',
   'clipSampleDone/aaa/T/cell08-gray_8x6 copy.png',
   'clipSampleDone/aaa/U/cell01-gray_10x1 copy.png',
   'clipSampleDone/aaa/U/cell01-gray_2x1 copy.png',
   'clipSampleDone/aaa/U/cell01-gray_3x0 copy.png',
   'clipSampleDone/aaa/U/cell01-gray_8x10 copy.png',
   'clipSampleDone/aaa/U/cell02-gray_0x3 copy.png',
   'clipSampleDone/aaa/U/cell02-gray_1x7 copy.png',
   'clipSampleDone/aaa/U/cell02-gray_3x9 copy.png',
   'clipSampleDone/aaa/U/cell02-gray_7x7 copy.png',
   'clipSampleDone/aaa/U/cell03-gray_1x0 copy.png',
   'clipSampleDone/aaa/U/cell03-gray_3x2 copy.png',
   'clipSampleDone/aaa/U/cell03-gray_7x0 copy.png',
   'clipSampleDone/aaa/U/cell03-gray_8x8 copy.png',
   'clipSampleDone/aaa/U/cell05-gray_1x4 copy.png',
   'clipSampleDone/aaa/U/cell05-gray_4x4 copy.png',
   'clipSampleDone/aaa/U/cell05-gray_4x8 copy.png',
   'clipSampleDone/aaa/U/cell05-gray_5x7 copy.png',
   'clipSampleDone/aaa/U/cell05-gray_8x2 copy 2.png',
   'clipSampleDone/aaa/U/cell05-gray_8x2.png',
   'clipSampleDone/aaa/U/cell05-gray_9x3 copy.png',
   'clipSampleDone/aaa/U/cell05-gray_9x3.png',
   'clipSampleDone/aaa/U/cell06-gray_5x8 copy.png',
   'clipSampleDone/aaa/U/cell07-gray_7x4 copy.png',
   'clipSampleDone/aaa/U/cell07-gray_8x0 copy.png',
   'clipSampleDone/aaa/U/cell08-gray_1x8 copy.png',
   'clipSampleDone/aaa/U/cell08-gray_8x10 copy.png',
   'clipSampleDone/aaa/U/cell08-gray_8x4 copy.png',
   'clipSampleDone/aaa/V/cell01-gray_1x8 copy.png',
   'clipSampleDone/aaa/V/cell01-gray_7x5 copy.png',
   'clipSampleDone/aaa/V/cell03-gray_3x4 copy.png',
   'clipSampleDone/aaa/V/cell04-gray_10x3 copy.png',
   'clipSampleDone/aaa/V/cell05-gray_6x3 copy.png',
   'clipSampleDone/aaa/V/cell07-gray_10x8 copy.png',
   'clipSampleDone/aaa/V/cell07-gray_8x5 copy.png',
   'clipSampleDone/aaa/W/cell01-gray_7x1 copy.png',
   'clipSampleDone/aaa/W/cell03-gray_0x6 copy.png',
   'clipSampleDone/aaa/W/cell04-gray_0x0 copy.png',
   'clipSampleDone/aaa/W/cell05-gray_7x1 copy.png',
   'clipSampleDone/aaa/W/cell08-gray_5x10 copy.png',
   'clipSampleDone/aaa/X/cell06-gray_9x2 copy.png',
   'clipSampleDone/aaa/X/cell07-gray_1x5 copy.png',
   'clipSampleDone/aaa/X/cell07-gray_7x8 copy.png',
   'clipSampleDone/aaa/Y/cell01-gray_2x7 copy.png',
   'clipSampleDone/aaa/Y/cell01-gray_2x7.png',
   'clipSampleDone/aaa/Y/cell02-gray_10x3 copy.png',
   'clipSampleDone/aaa/Y/cell02-gray_10x3.png',
   'clipSampleDone/aaa/Y/cell02-gray_10x6 copy.png',
   'clipSampleDone/aaa/Y/cell03-gray_3x0 copy.png',
   'clipSampleDone/aaa/Y/cell03-gray_5x10.png',
   'clipSampleDone/aaa/Y/cell04-gray_10x5.png',
   'clipSampleDone/aaa/Y/cell06-gray_1x3 copy.png',
   'clipSampleDone/aaa/Y/cell06-gray_1x3.tif',
   'clipSampleDone/aaa/Y/cell07-gray_5x1 copy.png',
   'clipSampleDone/aaa/Y/cell07-gray_5x1.png',
   'clipSampleDone/aaa/Y/cell08-gray_4x1 copy.png',
   'clipSampleDone/aaa/Y/cell08-gray_4x1.png',
   'clipSampleDone/aaa/Z/cell06-gray_9x6 copy.png',
   'clipSampleDone/aaa/Z/cell06-gray_9x6.png'
]

maxH = 0
maxW = 0
maxHDim = None
maxWDim = None
maxHDimFile = None
maxWDimFile = None

for file in fileList:
   img = cv2.imread(file, 0)
   if img is None:
      print "Skipping non-existent " + file
      continue;
   (h,w) = img.shape
   if h >= 75 and w >= 73:
      print "Skipping unmodified (%d,%d) from %s" % (h, w, file)
      continue
   if h >= 60 or w >= 60:
      print "Skipping outlier (%d,%d) from %s" % (h, w, file)
      continue
   if h > maxH:
      maxH = h
      maxHDim = (h,w)
      maxHDimFile = file
   if w > maxW:
      maxW = w
      maxWDim = (h,w)
      maxWDimFile = file
print "maxH=%d at (%d,%d) from %s; maxW=%d at (%d,%d) from %s" % (maxH, maxHDim[0], maxHDim[1], maxHDimFile, maxW, maxWDim[0], maxWDim[1], maxWDimFile)
